# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Lifesum-Challenge' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Lifesum-Challenge
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'UICountingLabel'

  target 'Lifesum-ChallengeTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'RxTest'
    pod 'RxBlocking'
  end

end
